### ISSUE TITLE
windows: binary add-on loading

### ISSUE THREAD

**Issue by imlucas** [mongodb-js/lone#14]
why is process.dlopen undefined?

```
load "C:\\Users\\lucas\\AppData\\Local\\bsonic\\node_modules\\bson\\ext\\win32\\ia32\\bson.node" for module "C:\\Users\\
lucas\\AppData\\Local\\bsonic\\node_modules\\bson\\ext\\win32\\ia32\\bson.node" extension ".node" handler undefined
js-bson: Error: The specified module could not be found.
C:\Users\lucas\AppData\Local\bsonic\node_modules\bson\ext\win32\ia32\bson.node
    at Module.load (module.js:360:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:368:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\lucas\AppData\Local\bsonic\node_modules\bson\ext\index.js:8:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:360:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:368:17)
load "C:\\Users\\lucas\\AppData\\Local\\bsonic\\node_modules\\bson\\build\\Release\\bson.node" for module "C:\\Users\\lu
cas\\AppData\\Local\\bsonic\\node_modules\\bson\\build\\Release\\bson.node" extension ".node" handler undefined
js-bson: Failed to load c++ bson extension, using pure JS version
```

**Comment by imlucas** [comment]
Figured it out. Fix will be #25
